apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mosquitto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mosquitto.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mosquitto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- if .Values.listeners.mqtt.enabled }}
            - name: mqtt
              containerPort: {{ .Values.listeners.mqtt.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.listeners.websocket.enabled }}
            - name: mqtt-ws
              containerPort: {{ .Values.listeners.websocket.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.listeners.mqttTls.enabled }}
            - name: mqtt-tls
              containerPort: {{ .Values.listeners.mqttTls.port }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
            {{- if .Values.auth.enabled }}
            - name: secrets
              mountPath: /mosquitto/config/passwords.conf
              subPath: passwords.conf
              readOnly: true
            - name: config
              mountPath: /mosquitto/config/acl.conf
              subPath: acl.conf
              readOnly: true
            {{- end }}
            {{- if and .Values.listeners.mqttTls.enabled .Values.listeners.mqttTls.tls }}
            - name: tls-certs
              mountPath: /mosquitto/certs/{{ .Values.listeners.mqttTls.tls.certKey | default "tls.crt" }}
              subPath: {{ .Values.listeners.mqttTls.tls.certKey | default "tls.crt" }}
              readOnly: true
            - name: tls-certs
              mountPath: /mosquitto/certs/{{ .Values.listeners.mqttTls.tls.keyKey | default "tls.key" }}
              subPath: {{ .Values.listeners.mqttTls.tls.keyKey | default "tls.key" }}
              readOnly: true
            {{- if .Values.listeners.mqttTls.tls.requireClientCerts }}
            - name: tls-certs
              mountPath: /mosquitto/certs/{{ .Values.listeners.mqttTls.tls.caKey | default "ca.crt" }}
              subPath: {{ .Values.listeners.mqttTls.tls.caKey | default "ca.crt" }}
              readOnly: true
            {{- end }}
            {{- end }}
            {{- if .Values.listeners.websocket.tls.enabled }}
            - name: tls-certs-ws
              mountPath: /mosquitto/certs-ws/{{ .Values.listeners.websocket.tls.certKey }}
              subPath: {{ .Values.listeners.websocket.tls.certKey }}
              readOnly: true
            - name: tls-certs-ws
              mountPath: /mosquitto/certs-ws/{{ .Values.listeners.websocket.tls.keyKey }}
              subPath: {{ .Values.listeners.websocket.tls.keyKey }}
              readOnly: true
            {{- if .Values.listeners.websocket.tls.requireClientCerts }}
            - name: tls-certs-ws
              mountPath: /mosquitto/certs-ws/{{ .Values.listeners.websocket.tls.caKey }}
              subPath: {{ .Values.listeners.websocket.tls.caKey }}
              readOnly: true
            {{- end }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              {{- if .Values.listeners.mqtt.enabled }}
              port: {{ .Values.listeners.mqtt.port }}
              {{- else if .Values.listeners.websocket.enabled }}
              port: {{ .Values.listeners.websocket.port }}
              {{- else if .Values.listeners.mqttTls.enabled }}
              port: {{ .Values.listeners.mqttTls.port }}
              {{- end }}
          readinessProbe:
            tcpSocket:
              {{- if .Values.listeners.mqtt.enabled }}
              port: {{ .Values.listeners.mqtt.port }}
              {{- else if .Values.listeners.websocket.enabled }}
              port: {{ .Values.listeners.websocket.port }}
              {{- else if .Values.listeners.mqttTls.enabled }}
              port: {{ .Values.listeners.mqttTls.port }}
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "mosquitto.fullname" . }}
        {{- if .Values.auth.enabled }}
        - name: secrets
          secret:
            {{- if .Values.auth.usersExistingSecret }}
            secretName: {{ .Values.auth.usersExistingSecret }}
            {{- else }}
            secretName: {{ include "mosquitto.fullname" . }}
            {{- end }}
        {{- end }}
        {{- if and .Values.listeners.mqttTls.enabled .Values.listeners.mqttTls.tls .Values.listeners.mqttTls.tls.secretName }}
        - name: tls-certs
          secret:
            secretName: {{ .Values.listeners.mqttTls.tls.secretName }}
        {{- end }}
        {{- if and .Values.listeners.websocket.tls.enabled .Values.listeners.websocket.tls.secretName }}
        - name: tls-certs-ws
          secret:
            secretName: {{ .Values.listeners.websocket.tls.secretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
